// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"time"
)

type Identifiable[T any] interface {
	GetID() T
}

type Author struct {
	ID        int64
	FirstName string
	LastName  string
	BirthDate time.Time
}

func (s Author) GetID() int64 {
	return s.ID
}

type Book struct {
	BookID    int64
	Isbn      string
	BookType  interface{}
	Title     string
	Year      int64
	Available interface{}
	Tags      string
}

type BookAuthor struct {
	BookID   int64
	AuthorID int64
}
