// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"

	"github.com/lib/pq"
)

const getBook = `-- name: GetBook :one
SELECT books.book_id, books.isbn, books.book_type, books.title, books.year, books.available, books.tags, NULL from books WHERE book_id = ?
`

type GetBookRow struct {
	BookID         interface{}
	Isbn           string
	BookType       interface{}
	Title          string
	Year           int64
	Available      interface{}
	Tags           string
	GetBookAuthors []Author
}

func (q *Queries) GetBook(ctx context.Context, bookID interface{}) (GetBookRow, error) {
	row := q.db.QueryRowContext(ctx, getBook, bookID)
	var i GetBookRow
	err := row.Scan(
		&i.BookID,
		&i.Isbn,
		&i.BookType,
		&i.Title,
		&i.Year,
		&i.Available,
		&i.Tags,
		pq.Array(&i.GetBookAuthors),
	)
	return i, err
}

const getBookAuthors = `-- name: GetBookAuthors :many
SELECT authors.id, authors.first_name, authors.last_name, authors.birth_date FROM book_authors 
INNER JOIN authors ON book_authors.author_id = authors.id
WHERE book_authors.book_id = ?
`

func (q *Queries) GetBookAuthors(ctx context.Context, bookID int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getBookAuthors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
